server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/okr?useUnicode=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: zgku
    password: 199594zgk


mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
